fill ~2 ~ ~2 ~-2 ~ ~-2 wheat ["growth"=7] replace wheat ["growth"=6]
fill ~2 ~ ~2 ~-2 ~ ~-2 wheat ["growth"=6] replace wheat ["growth"=5]
fill ~2 ~ ~2 ~-2 ~ ~-2 wheat ["growth"=5] replace wheat ["growth"=4]
fill ~2 ~ ~2 ~-2 ~ ~-2 wheat ["growth"=4] replace wheat ["growth"=3]
fill ~2 ~ ~2 ~-2 ~ ~-2 wheat ["growth"=3] replace wheat ["growth"=2]
fill ~2 ~ ~2 ~-2 ~ ~-2 wheat ["growth"=2] replace wheat ["growth"=1]
fill ~2 ~ ~2 ~-2 ~ ~-2 wheat ["growth"=2] replace wheat ["growth"=0]


fill ~2 ~ ~2 ~-2 ~ ~-2 beetroot ["growth"=7] replace beetroot ["growth"=6]
fill ~2 ~ ~2 ~-2 ~ ~-2 beetroot ["growth"=6] replace beetroot ["growth"=5]
fill ~2 ~ ~2 ~-2 ~ ~-2 beetroot ["growth"=5] replace beetroot ["growth"=4]
fill ~2 ~ ~2 ~-2 ~ ~-2 beetroot ["growth"=4] replace beetroot ["growth"=3]
fill ~2 ~ ~2 ~-2 ~ ~-2 beetroot ["growth"=3] replace beetroot ["growth"=2]
fill ~2 ~ ~2 ~-2 ~ ~-2 beetroot ["growth"=2] replace beetroot ["growth"=1]
fill ~2 ~ ~2 ~-2 ~ ~-2 beetroot ["growth"=2] replace beetroot ["growth"=0]


fill ~2 ~ ~2 ~-2 ~ ~-2 carrots ["growth"=7] replace carrots ["growth"=6]
fill ~2 ~ ~2 ~-2 ~ ~-2 carrots ["growth"=6] replace carrots ["growth"=5]
fill ~2 ~ ~2 ~-2 ~ ~-2 carrots ["growth"=5] replace carrots ["growth"=4]
fill ~2 ~ ~2 ~-2 ~ ~-2 carrots ["growth"=4] replace carrots ["growth"=3]
fill ~2 ~ ~2 ~-2 ~ ~-2 carrots ["growth"=3] replace carrots ["growth"=2]
fill ~2 ~ ~2 ~-2 ~ ~-2 carrots ["growth"=2] replace carrots ["growth"=1]
fill ~2 ~ ~2 ~-2 ~ ~-2 carrots ["growth"=2] replace carrots ["growth"=0]


fill ~2 ~ ~2 ~-2 ~ ~-2 potatoes ["growth"=7] replace potatoes ["growth"=6]
fill ~2 ~ ~2 ~-2 ~ ~-2 potatoes ["growth"=6] replace potatoes ["growth"=5]
fill ~2 ~ ~2 ~-2 ~ ~-2 potatoes ["growth"=5] replace potatoes ["growth"=4]
fill ~2 ~ ~2 ~-2 ~ ~-2 potatoes ["growth"=4] replace potatoes ["growth"=3]
fill ~2 ~ ~2 ~-2 ~ ~-2 potatoes ["growth"=3] replace potatoes ["growth"=2]
fill ~2 ~ ~2 ~-2 ~ ~-2 potatoes ["growth"=2] replace potatoes ["growth"=1]
fill ~2 ~ ~2 ~-2 ~ ~-2 potatoes ["growth"=2] replace potatoes ["growth"=0]

fill ~2 ~ ~2 ~-2 ~ ~-2 pumpkin_stem ["growth"=7] replace pumpkin_stem ["growth"=6]
fill ~2 ~ ~2 ~-2 ~ ~-2 pumpkin_stem ["growth"=6] replace pumpkin_stem ["growth"=5]
fill ~2 ~ ~2 ~-2 ~ ~-2 pumpkin_stem ["growth"=5] replace pumpkin_stem ["growth"=4]
fill ~2 ~ ~2 ~-2 ~ ~-2 pumpkin_stem ["growth"=4] replace pumpkin_stem ["growth"=3]
fill ~2 ~ ~2 ~-2 ~ ~-2 pumpkin_stem ["growth"=3] replace pumpkin_stem ["growth"=2]
fill ~2 ~ ~2 ~-2 ~ ~-2 pumpkin_stem ["growth"=2] replace pumpkin_stem ["growth"=1]
fill ~2 ~ ~2 ~-2 ~ ~-2 pumpkin_stem ["growth"=2] replace pumpkin_stem ["growth"=0]

fill ~2 ~ ~2 ~-2 ~ ~-2 melon_stem ["growth"=7] replace melon_stem ["growth"=6]
fill ~2 ~ ~2 ~-2 ~ ~-2 melon_stem ["growth"=6] replace melon_stem ["growth"=5]
fill ~2 ~ ~2 ~-2 ~ ~-2 melon_stem ["growth"=5] replace melon_stem ["growth"=4]
fill ~2 ~ ~2 ~-2 ~ ~-2 melon_stem ["growth"=4] replace melon_stem ["growth"=3]
fill ~2 ~ ~2 ~-2 ~ ~-2 melon_stem ["growth"=3] replace melon_stem ["growth"=2]
fill ~2 ~ ~2 ~-2 ~ ~-2 melon_stem ["growth"=2] replace melon_stem ["growth"=1]
fill ~2 ~ ~2 ~-2 ~ ~-2 melon_stem ["growth"=2] replace melon_stem ["growth"=0]